outputs:
  tas:
    shortname: tas
    longname: Temperature
    unit: K
    lim:
      values: [-6, 6] 
      rmse: [0, 1.75]
      mae: [0, 1.5]
      temporal_correlation: [-1, 1]
      mean_error: [-0.8, 0.8]

    colors:
      values: 'coolwarm'
      rmse: 'viridis'
      mae: 'viridis'
      temporal_correlation: 'coolwarm'
      mean_error: 'coolwarm'

  pr:
    shortname: pr
    longname: Precipitation
    unit: mm/day
    lim:
      values: [-4, 4] 
      rmse: [0, 3]
      mae: [0, 2.5]
      temporal_correlation: [-1, 1]
      mean_error: [-0.6, 0.6]

    colors:
      values: 'BrBG'
      rmse: 'viridis'
      mae: 'viridis'
      temporal_correlation: 'coolwarm'
      mean_error: 'coolwarm'

  pr90:
    shortname: pr90
    longname: Extreme precipitation
    unit: 'mm/day'
    lim:
      values: [-8, 8] 
      rmse: [0, 8]
      mae: [0, 6.5]
      temporal_correlation: [-1, 1]
      mean_error: [-1.5, 1.5]

    colors:
      values: 'BrBG'
      rmse: 'viridis'
      mae: 'viridis'
      temporal_correlation: 'coolwarm'
      mean_error: 'coolwarm'

  diurnal_temperature_range: 
    shortname: dtr
    longname: Diurnal temprature range
    unit: K
    lim:
      values: [-2, 2] 
      rmse: [0, 1.25]
      mae: [0, 1.1]
      temporal_correlation: [-1, 1]
      mean_error: [-1, 1]

    colors:
      values: 'coolwarm'
      rmse: 'viridis'
      mae: 'viridis'
      temporal_correlation: 'coolwarm'
      mean_error: 'coolwarm'

inputs:
  CO2:
    longname: | 
      Cumulative anthropogenic CO2 
      emissions since 1850
    unit: GtCO2
    lim:
      values: [0, 10000]
  CH4:
    longname: | 
      Anthropogenic CH4 emissions
    unit: GtCH4 / year
    lim:
      values: [0, 0.8]
  SO2:
    longname: | 
      Anthropogenic SO2 
      emissions
    unit: TgSO2 / year
    lim:
      values: [0, 8e-12]
  BC: 
    longname: |
      Anthropogenic BC 
      emissions
    unit: TgBC / year 
    lim:
      values: [0, 5e-13]
