data:
  exp : 'exp1'
  simus: ['hist-GHG', 'hist-aer','ssp126', 'ssp245', 'ssp370', 'ssp370-lowNTCF', 'ssp585', historical]
  slider: 10
  len_historical: 165 
  raw_dir: '/scratch/globc/garcia/ClimateBench/rawdata/train_val'
  dataset_dir: '/scratch/globc/garcia/ClimateBench/dataset/dataset_exp1'
  vars_to_predict: ['diurnal_temperature_range', 'tas', 'pr', 'pr90']
  vars: ['CO2', 'SO2', 'CH4', 'BC']

model:
  arch: 'lstm'
  learning_rate: 0.001
  max_epochs: 30
  batch_size: 16
  slider: 10
  runs_dir: '/scratch/globc/garcia/ClimateBench/runs/exp1/lstm_5scenarios_diurnal_temperature_range'
  model: 'lstm'
  var_to_predict: 'diurnal_temperature_range'
  test_name : 'lstm_5scenarios_diurnal_temperature_range'
  simus_train: ['ssp126', 'ssp370', 'ssp585', 'hist-GHG', 'hist-aer', 'historical']
  simus_test: ['ssp245']
  img_size: [96, 144]
  scheduler_step_size: 50
  scheduler_gamma: 0.1
